chore: clean up after stow introduced

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
 
+# 1 is Dry, 0 is Wet
 dry_run="1"
 
 # Where the config is going to be installed TO
@@ -32,6 +33,10 @@ log() {
     fi
 }
 
+log "//////////////////"
+log "//// Setup"
+log "/////////////"
+log "// Moving dotfiles"
 log "----------- $DEV_ENV -----------"
 
 # ensure dev-env script is in $HOME/personal
@@ -41,75 +46,24 @@ else
     log "Copying dev-env script to ~/personal"
 fi
 
-## Copy Configs
-# Find all directories under DEV_ENV
-# For each directory
-#   Get the path to an existing dir of that name under $XDG_CONFIG_HOME
-#   Remove the existing directory (destination)
-#   Copy the directory from DEV_ENV to the destination
-
-# Params: from, to
-copy_configs() {
-    from=$1
-    to=$2
-
-    log "Copying Configs"
-    log "  from:    $from"
-    log "  to:      $to"
-
-    # change to "from" directory
-    pushd $1 &> /dev/null
-    (
-        # find directories in the $1 path
-        configDirs=`find . -mindepth 1 -maxdepth 1 -type d`
-        for configDir in $configDirs; do
-            # Clean up path
-            configDir=$(basename $configDir)
-
-            # Bash Wizardry for "to" path
-            destinationDir=${2%/}/${configDir#}
-
-            # Remove old Directory
-            log "  Removing Old Dir (from)"
-            log "    existing (potentially):  $destinationDir"
-            if [[ $dry_run == "0" ]]; then
-                rm -rf $destinationDir
-            fi
-
-            # Copy contents of "from" into destination
-            log "  Copying Directory (to)"
-            log "    from: $1/$configDir"
-            log "    to:   $destinationDir"
-            if [[ $dry_run == "0" ]]; then
-                cp -R ./$configDir $destinationDir/
-            fi
-            ls -la $destinationDir
-        done
-    )
-    # return to previous directory
-    popd &> /dev/null
-}
-echo "Copy Configs $DEV_ENV/env to $XDG_CONFIG_HOME"
-# copy_configs $DEV_ENV/env $XDG_CONFIG_HOME
-
 ## Ensure Stow is installed?
-log "Checking for stow"
-which stow &>/dev/null
-if [[ $? == 1 ]]; then
-    log "stow not found - installing"
+log "Stow"
+log "  Checking for stow"
+if ! hash stow; then
+    log "    stow not found - installing"
 
     if [[ $dry_run == "0" ]]; then
-        log "  running: sudo apt install stow -y"
-    else
         sudo apt install stow -y
+    else
+        log "  sudo apt install stow -y"
     fi
 else
-    log "Found stow"
+    log "  Found stow"
 fi
 ## Should we run stow in here?
-log "Running stow"
+log "  Running stow"
 if [[ $dry_run == "0" ]]; then
-    log "  stow disabled"
+    log "    \`stow .local nvim tmux zsh\` disabled"
     # stow -d $DEV_ENV/env \
         #     -t $XDG_CONFIG_HOME \
         #     .local \
@@ -117,35 +71,21 @@ if [[ $dry_run == "0" ]]; then
         #     tmux \
         #     zsh
 else
+    log "    stow simulating [DRY_RUN]"
     stow -nv \
         -d $DEV_ENV/env \
         -t $XDG_CONFIG_HOME \
         .local \
         nvim \
         tmux \
-        zsh
+        zsh \
+        --ignore .git 
 fi
 
-# Do this for .config dir
-# Do this for .local dir
+if [[ $dry_run == "0" ]]; then
+    log "  running ./run --real is disabled"
+    # ./run --real
+else
+    ./run 
+fi
 
-## Copy Individual Files
-# Remove existing file
-# Copy file in DEV_ENV to $XDG_CONFIG_HOME
-
-# Do this for .zshrc
-# Do this for this script
-
-## Copy Directories
-# Find all dirs in DEV_ENV
-# For each directory
-#   Remove existing directory from $XDG_CONFIG_HOME
-#   Copy DEV_ENV to $XDG_CONFIG_HOME
-
-# Do this for .config directory
-
-### Run Script
-# Get executables from the runs directory
-# Filter out items passed via grep
-# Run the script
-# E.g. ready-tmux
